main_app/urls.py
from django.urls import path
from . import views
	
urlpatterns = [
	path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('campsites/', views.campsites_index, name='index'),
    path('campsites/<int:campsite_id>/', views.campsites_detail, name='detail'),
    path('campsites/create/', views.CampsiteCreate.as_view(), name='campsites_create'),
    path('campsites/<int:pk>/update/', views.CampsiteUpdate.as_view(), name='campsites_update'),
    path('campsites/<int:pk>/delete/', views.CampsiteDelete.as_view(), name='campsites_delete'),
    path('campsites/<int:campsite_id>/add_trail/', views.add_trail, name='add_trail'),
    path('campsites/<int:campsite_id>/add_photo/', views.add_photo, name='add_photo'),
    path('campsites/<int:campsite_id>/add_amenity/<int:amenity_id>/', views.add_amenity, name='add_amenity'),
    path('campsites/<int:campsite_id>/remove_amenity/<int:amenity_id>/', views.remove_amenity, name='remove_amenity'),
    path('amenities/', views.AmenityList.as_view(), name='amenities_index'),
    path('amenities/create/', views.AmenityCreate.as_view(), name='amenities_create'),
    path('amenities/<int:pk>/delete/', views.AmenityDelete.as_view(), name='amenities_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

naturenotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Amenity(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('amenities_detail', kwargs={'pk': self.id})


class Campsite(models.Model):
    name = models.CharField(max_length=150)
    location = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    amenities = models.ManyToManyField(Amenity)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'campsite_id': self.id})
    

class Trail(models.Model):
    name = models.CharField(max_length=100)
    length = models.CharField(max_length=50)
    campsite = models.ForeignKey(Campsite, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_trail_display()} @ {self.campsite}'


class Photo(models.Model):
    url = models.CharField(max_length=200)
    campsite = models.ForeignKey(Campsite, on_delete=models.CASCADE)

    def __str__(self):
        return f'Photo for campsite_id: {self.campsite_id} @{self.url}'

main_app/forms.py
from django.forms import ModelForm
from .models import Trail, Amenity 

class TrailForm(ModelForm):
  class Meta:
    model = Trail
    fields = ['name', 'length']

class AmenityForm(ModelForm):
  class Meta:
    model = Amenity
    fields= ['name']

main_app/views.py
import os
import uuid
import boto3
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Campsite, Amenity, Photo
from .forms import TrailForm, AmenityForm


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


@login_required
def campsites_index(request):
    campsites = Campsite.objects.filter(user=request.user)
    return render(request, 'campsites/index.html', 
        {'campsites': campsites
    })


@login_required
def campsites_detail(request, campsite_id):
    campsite = Campsite.objects.get(id=campsite_id)
    id_list = campsite.amenities.all().values_list('id')
    amenities_campsite_doesnt_have = Amenity.objects.exclude(id__in=id_list)
    trail_form = TrailForm()
    return render(request, 'campsites/detail.html', {
        'campsite': campsite, 'trail_form': trail_form, 'amenities': amenities_campsite_doesnt_have
    })


class CampsiteCreate(LoginRequiredMixin, CreateView):
    model = Campsite
    fields = ['name', 'location', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CampsiteUpdate(LoginRequiredMixin, UpdateView):
    model = Campsite
    fields = ['location', 'description']


class CampsiteDelete(LoginRequiredMixin, DeleteView):
    model = Campsite
    success_url = '/campsites'


@login_required
def add_trail(request, campsite_id):
    form = TrailForm(request.POST)
    if form.is_valid():
        new_trail = form.save(commit=False)
        new_trail.campsite_id = campsite_id
        new_trail.save()
    return redirect('detail', campsite_id=campsite_id)


class AmenityList(LoginRequiredMixin, ListView):
   model = Amenity


class AmenityCreate(LoginRequiredMixin, CreateView):
   model = Amenity
   fields = '__all__'
   success_url = '/amenities'


class AmenityDelete(LoginRequiredMixin, DeleteView):
   model = Amenity
   success_url = '/amenities'


@login_required
def add_amenity(request, campsite_id, amenity_id):
   Campsite.objects.get(id=campsite_id).amenities.add(amenity_id)
   return redirect('detail', campsite_id=campsite_id)


@login_required
def remove_amenity(request, campsite_id, amenity_id):
   Campsite.objects.get(id=campsite_id).amenities.remove(amenity_id)
   return redirect('detail', campsite_id=campsite_id)
   

@login_required
def add_photo(request, campsite_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      Photo.objects.create(url=url, campsite_id=campsite_id)
    except Exception as e:
      print('An error occurred uploading file to S3')
      print(e)
  return redirect('detail', campsite_id=campsite_id)


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

{% load static %}

<div id="about">
    <h1>About <span class="logo">NatureNotes</span></h1>

    <h3>Getting outdoors doesn't have to be a chore!</h3>
    <p>NatureNotes is an app designed to make your camping experience more enjoyable and organized.</p>
    <p>Whether you're an avid camper or just starting out, NatureNotes offers a user-friendly platform to create and manage your personalized list of campsites completed with amenities and nearby hiking trails.</p>
</div>


<div class="corner-images">
  <div class="corner-image top-left">
    <img src="{% static 'images/jesse-gardner-wTVr4HR4SBI-unsplash.jpg' %}" alt="Orange tent with mountains" />
</div>
  <div class="corner-image top-right">
    <img src="{% static 'images/image2.jpg' %}" alt="Image 2">
  </div>
  <div class="corner-image bottom-left">
    <img src="{% static 'images/image3.jpg' %}" alt="" />

  </div>
  <div class="corner-image bottom-right">
    <img src="{% static 'images/image4.jpg' %}" alt="img4"/>
  </div>

</div>


{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nature Notes</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Khula:wght@400;600;700&family=Montserrat+Subrayada&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <main>
        <div class="container">
            <div>   
                <label class="hamburger-menu">
                    <input type="checkbox">
                </label>             
                <aside class="sidebar">
                    <div><a href="{% url 'about' %}">About</a></div>
                    {% if user.is_authenticated %}
                        <div><a href="{% url 'index' %}">My Campsites</a></div>
                        <div><a href="{% url 'campsites_create' %}">Add a Campsite</a></div>
                        <div><a href="{% url 'amenities_index' %}">All Amenities</a></div>
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <div class="btn"><a href="{% url 'signup' %}">Sign Up</a></div>
                        <div class="login"><a href="{% url 'login' %}">Log In</a></div>
                    {% else %}
                        <div class="login"><a href="{% url 'logout' %}">Log Out</a></div>
                    {% endif %}
                </aside>
            </div> 
            <div>
                <h1 id="title-logo" class="logo"><a href="{% url 'home' %}">NatureNotes</a></h1>
            </div>
        </div>
       {% block content %}
       {% endblock %}
    </main>
    <footer id="footer">Created by ACS Designs 2023</footer>
</body>
</html>

main_app/templates/campsites/detail.html
{% extends 'base.html' %}
{% block content %}

{% load static %}

<div class="detail">
    <h1 id="detail-header">{{ campsite.name }} Details</h1>

    <div class="campsite-info">
        <div class="photo">
            {% for photo in campsite.photo_set.all %}
                <img id="user-campsite-photo" src="{{photo.url}}">
            {% empty %}
                <img id="placeholder-photo" src="{% static 'images/take-more-photos.png' %}" style="width:12rem; height:10rem;">
                <form action="{% url 'add_photo' campsite.id %}" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <input type="file" name="photo-file">
                    <br><br>
                    <button type="submit" class="btn">Upload Photo</button>
                </form>
            {% endfor %}
        </div>
        <div class="card" id="detail-card">
            <p>{{ campsite.location }}</p>
            <p>{{ campsite.description }}</p>
            <a class="btn" href="{% url 'campsites_update' campsite.id %}">Edit</a>
            <a class="btn" href="{% url 'campsites_delete' campsite.id %}">Delete</a>
        </div>
    </div>
    <div class="trail">
        <h3>Nearby Trails</h3>
        {% for trail in campsite.trail_set.all %}
            <p>{{ trail.name }} | {{ trail.length }}</p>
        {% endfor %}
        <form action="{% url 'add_trail' campsite.id %}" method="POST">
            {% csrf_token %}
            {{ trail_form.as_p }}
            <input type="submit" class="btn" value="Add a Trail">
        </form>
    </div>
    {% comment %} <a href="{% url 'add_amenity' campsite.id %}">Add Amenity</a> {% endcomment %}

    <div class="amenities">
      <h3>Amenities</h3>
      {% if campsite.amenities.count %}
        {% for amenity in campsite.amenities.all %}
            <span>{{ amenity.name }}
                <form action="{% url 'remove_amenity' campsite.id amenity.id %}" method="POST" style="display:inline-block">
                    {% csrf_token %}
                    <button type="submit">x</button>
                </form>
            </span>
        {% endfor %}
      {% else %}
        <h5>No Amenities</h5>
      {% endif %}
    </div>
    <div class="add-amenities">
        <h3>Add Amenities</h3>
        {% if amenities.count %}
          {% for amenity in amenities.all %}
            <span class="amenity-btn">{{ amenity.name }}
                <form action="{% url 'add_amenity' campsite.id amenity.id %}" method="POST" style="display:inline-block">
                    {% csrf_token %}
                    <button type="submit">+</button>
                </form>
            </span>
          {% endfor %}
        {% else %}
          <h5>{{campsite.name}} already has all available amenities. <a href="{% url 'amenities_index' %}" style="color:#47C67A">Add more!</a></h5>
        {% endif %}     
    </div>
    <a href="{% url 'index' %}">Back to All Campsites</a>
</div>
{% endblock %}

main_app/templates/campsites/index.html
{% extends 'base.html' %}
{% block content %}

{% load static %}

<div id="index">
    <div class="text">
        <h1>My Campsites</h1>

        {% for campsite in campsites %}
            <a href="{% url 'detail' campsite.id %}">
                <div class="card" id="index-card">
                    <p>
                        {% for photo in campsite.photo_set.all %}
                            <img id="index-photo" src="{{photo.url}}">
                        {% empty %}
                            <img id="placeholder-photo" src="{% static 'images/take-more-photos.png' %}" style="width:12rem; height:10rem;">
                        {% endfor %}
                    </p>
                    <div class="card-text">
                        <p><span class="card-title">{{ campsite.name }}</span> | {{ campsite.location }}</p>
                        <p class="description">{{ campsite.description }}</p>
                    </div>
                </div>
            </a>
        {% empty %}
            <p id="no-campsites">You have no campsites.</p>
        {% endfor %}
        <a id="add-campsite" href="{% url 'campsites_create' %}">+ Add</a>
    </div>

</div>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

{% load static %}

<div id="home-page">
    <img id="home-image" src="{% static 'images/alex-shutin-kKvQJ6rK6S4-unsplash.jpg' %}" alt="blue mountains" style="height: 75%; width: 100%; " >
    {% if not user.is_authenticated %}
        <button class="login home-btn"><a href="{% url 'about' %}">Start here</a></button>
    {% else %}
        <button class="login home-btn"><a href="{% url 'index' %}">See My Campsites</a></button>
    {% endif %}
</div>

{% endblock %}

main_app/templates/main_app/amenity_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="delete-form">
  <h1>Delete Amenity</h1>

  <h4>Are you sure you want to delete <span>{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'amenities_index' %}">Cancel</a>
  </form>
</div>
{% endblock %}

main_app/templates/main_app/amenity_form.html
{% extends 'base.html' %}

{% block content %}

<div class="edit-add-form">
  {% if object %}
    <h1>Edit {{object.name}}</h1>
  {% else %}
    <h1>Add Amenity</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
</div>
{% endblock %}

main_app/templates/main_app/amenity_list.html
{% extends 'base.html' %}
{% block content %}

<div class="amenity-detail">

  <h1>Amenity List</h1>
  <div>
  {% for amenity in amenity_list %}
    <span>
      {{ amenity.name }}  
      <a href="{% url 'amenities_delete' amenity.id %}">x</a>
    </span>
  {% endfor %}
  </div>
  <a class="btn" href="{% url 'amenities_create' %}">Add New Amenity</a>

</div>

{% endblock %}

main_app/templates/main_app/campsite_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="delete-form">

    <h1>Delete Campsite</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn">
        <a href="{% url 'detail' campsite.id %}">Cancel</a>
    </form>

</div>

{% endblock %}

main_app/templates/main_app/campsite_form.html
{% extends 'base.html' %}
{% block content %}

<div class="edit-add-form">

  {% if object %}
    <h1>Edit <span>{{ object.name }}</span></h1>
  {% else %}
    <h1>Add Campsite</h1>
  {% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>

</div>

{% endblock %}